(setq org-journal-dir "~/org/journals/")
(setq org-journal-date-format "%A, %d %B %Y")
(setq org-journal-file-format "%Y_%m_%d.org")

;(set-input-method "russian-computer") 
;(add-hook 'minibuffer-setup-hook (lambda () (set-input-method "russian-computer")))
;(activate-input-method "russian-computer")

(setq filePath (concat org-journal-dir (format-time-string "%Y_%m_%d.org")))
(global-set-key (kbd "C-c j")
    (lambda () 
        (interactive) 
        (find-file filePath)
    )
)
